version: '3.8'

services:
  app:
    build: .
    container_name: tribunal_de_poche_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=tribunal;User=root;Password=root

  db:
    image: mysql:8
    container_name: tribunal_de_poche_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tribunal
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
